### ISSUE TITLE
Handover to Community

### ISSUE THREAD

**Issue by dericofilho** [phpfmt/sublime-phpfmt#167]
(Un)fortunatelly, I have been coding less and less in PHP. I understand
there is a small community around both sublime-phpfmt and php.tools.

Thus, I am calling all people interested in these tools to help me to
keep them alive.

Right now, I do not have any documentation to help you to provide support
and to propose PRs. But as soon as I see people taking action, I shall
help them to write such documentation and implement improvements on these
tools.

Eventually, I plan to move both projects to an independent account and
to have it run by a maintenance team.

Please! Take action and support these projects.

**Comment by iamntz** [comment]
Maybe moving it to Sublime Organization? 

https://github.com/SublimeText

**Comment by dericofilho** [comment]
I have nothing against the idea. But I would like to setup a group of contributors first - and then this group would choose what to do with this repo.
