### ISSUE TITLE
it can't work for wind7

### ISSUE THREAD

**Issue by ppker** [phpfmt/sublime-phpfmt#174]
this is my config

{
	"disable_auto_align": false,
	"enable_auto_align": true,
	"format_on_save": true,
	"php55compat": true,
	"php_bin": "C:/wamp/bin/php/php5.5.12/php.exe",
	"psr1": true,
	"version": 3
}

i use it .my code is not format

**Comment by dericofilho** [comment]
@ppker it seems you are using a very old version of the plugin. Could you please upgrade to latest? Then paste here the piece of code that's failing, and the output of `phpfmt: troubleshoot information`

**Comment by dericofilho** [comment]
If I don't hear until July 24th, I shall close this issue.

**Comment by ppker** [comment]
I'm sorry that I forget to tell you about it. I'm going to try again that.
