### ISSUE TITLE
error: Warning. PHP 5.6 or newer is required. Please, upgrade your local PHP installation.

### ISSUE THREAD

**Issue by fhefh2009** [phpfmt/sublime-phpfmt#178]
when i use sublimetext3 save php file, it shows "Warning.
PHP 5.6 or newer is required.
Please, upgrade your local PHP installation."

sublimetext3 version: build 3065

**Comment by AntyRace** [comment]
You have to upgrade local environment php to 5.6, then in config:
"php_bin": "/usr/local/bin/php" - set your local path to php 5.6

Regards
Anty

**Comment by phpfmt** [comment]
Fixed, I suppose right?
