### ISSUE TITLE
Wrong handling at cleanup brackets

### ISSUE THREAD

**Issue by ckeyer** [phpfmt/sublime-phpfmt#179]
$ php -v
PHP 5.6.4-4ubuntu6.2 (cli)

$ subl -v
Sublime Text Build 3083

before:
        <?php
        require_once(dirname(__FILE__) . '/../../midlayer/test.php');

phpfmt , then
        <?php
        require_once dirname(__FILE__ . '/../../midlayer/test.php');

It's a wrong handling

**Comment by ckeyer** [comment]
* asdhfas 
* dsaf 

## sdfasdf

    asdf
        asdfsdfa

        asdfsdfa
        asdfsdfa

**Comment by phpfmt** [comment]
Please, refer to https://github.com/phpfmt/php.tools/issues/50
