### ISSUE TITLE
Error at cleanup brackets

### ISSUE THREAD

**Issue by ckeyer** [phpfmt/sublime-phpfmt#180]
$ php -v
PHP 5.6.4-4ubuntu6.2 (cli)

$ subl -v
Sublime Text Build 3083

before:

        <?php
        require_once(dirname(__FILE__) . '/../../midlayer/test.php');

phpfmt , then

        <?php
        require_once dirname(__FILE__ . '/../../midlayer/test.php');

It's a wrong handling

**Comment by phpfmt** [comment]
@ckeyer Hi, I am sorry for this inconvenience. It is not entirely wrong. Please, follow the instructions at https://github.com/phpfmt/php.tools/issues/49

**Comment by phpfmt** [comment]
@ckeyer please, upgrade.
