### ISSUE TITLE
For loop formatting error

### ISSUE THREAD

**Issue by sjdaws** [phpfmt/sublime-phpfmt#181]
I have a for loop like this:
`for ($i = 0; ($i < $PER_PAGE) && ($i < count($users)); ++$i) {`

On save phpfmt changes it to:
`for ($i = 0;($i < $PER_PAGE) && ($i < count($users)); ++$i) {`

PHPCS complains saying there should be a space after `0;`.

My settings:
```
{
	"debug": true,
	"format_on_save": false,
	"passes":
	[
		"AlignDoubleArrow",
		"AlignDoubleSlashComments",
		"AutoPreincrement",
		"ClassToSelf",
		"DoubleToSingleQuote",
		"GeneratePHPDoc",
		"MergeElseIf",
		"PrettyPrintDocBlocks",
		"PSR2LnAfterNamespace",
		"ReturnNull",
		"SpaceBetweenMethods",
		"WrongConstructorName",
		"ReindentSwitchBlocks"
	],
	"php_bin": "/usr/local/bin/php",
	"psr1": true,
	"psr1_naming": false,
	"psr2": true,
	"version": 4
}
```

Thanks

**Comment by dericofilho** [comment]
@sjdaws please, upgrade to https://github.com/phpfmt/sublime-phpfmt/commit/4bcaf771455a83aaf9e0931ac809086d5cf6dcc7

**Comment by sjdaws** [comment]
@dericofilho confirmed fixed. Thanks for the quick update.

**Comment by dericofilho** [comment]
@sjdaws please, consider contributing both for sublime-phpfmt and php.tools. Thanks for using them.
