### ISSUE TITLE
bugs come back

### ISSUE THREAD

**Issue by lichunqiang** [phpfmt/sublime-phpfmt#182]
Hi, 

The sublime upgrade this tool to the latest version, but some bug is back which is solved before.

like #175 #128 #127 .....

**Comment by dericofilho** [comment]
@lichunqiang please, use troubleshoot command and paste here its contents.

**Comment by dericofilho** [comment]
@lichunqiang Please, consider adding to your configuration file:

```
...
"passes": ["ReindentAndAlignObjOps"],
...
```

**Comment by lichunqiang** [comment]
a ha...

but before upgrade, it works fine.

So, we must passed the veriable params to `passes` now ?

**Comment by dericofilho** [comment]
That's why I issued a major upgrade, because it was a BC breaking change.

**Comment by lichunqiang** [comment]
:+1:  thanks~
