### ISSUE TITLE
brackets position in function declarations

### ISSUE THREAD

**Issue by freinn** [phpfmt/sublime-phpfmt#183]
Hi!

reading [this docs](http://www.php-fig.org/psr/psr-1/) I see brackets are written in distinct positions respect to that they are in for loops or if.

**Comment by ccirello** [comment]
I am afraid you're not clear on your request. 

But have you considered activating PSR1 and PSR2 modes?

**Comment by freinn** [comment]
Didn't know that modes exists. Thanks.
