### ISSUE TITLE
GeneratePHPDoc Indentation

### ISSUE THREAD

**Issue by rjp2525** [phpfmt/sublime-phpfmt#184]
If a function does not already have a PHPDoc and I format the file, it inserts without any indentation:

```php
/**
 * @return mixed
 */
    public function test()
    {
        return $this->example;
    }
```

requiring a second format to automatically indent the comment:

```php
    /**
     * @return mixed
     */
    public function test()
    {
        return $this->example;
    }
```

**Comment by ccirello** [comment]
@rjp2525 Please, upgrade to https://github.com/phpfmt/sublime-phpfmt/releases/tag/7.4.0
