### ISSUE TITLE
Sync phpfmt.sublime-settings on different os (win and linux) -> wrong php path

### ISSUE THREAD

**Issue by Heart1010** [phpfmt/sublime-phpfmt#185]
I sync my installed packages across different machines via dropbox described https://packagecontrol.io/docs/syncing

Problem now is one pc is win10 the other linux.

So on my windows pc I need ```"php_bin": "C:/PHP/php.exe"``` in my phpfmt.sublime-settings and on the linux pc ```"php_bin": "/usr/bin/php"```

Now I have always the problem of a false php path on one pc ;)!

Can I handle that scenario in any way!? Provide a win and a linux path in phpfmt.sublime-settings or something like that?

**Comment by ccirello** [comment]
Yes. Install PHP in $PATH/%PATH% and make php_bin empty
