### ISSUE TITLE
Feature:Arranging namespaces based on length

### ISSUE THREAD

**Issue by olimorris** [phpfmt/sublime-phpfmt#186]
Firstly, thank the lord for this package. An absolute life saver.

So currently I toggle this on save and the package quite nicely rearranges my namespaces into alphabetical order like so:
```
use App\Http\Requests\JobRequest;
use App\RocketCandy\Contracts\Bid;
use App\RocketCandy\Contracts\Job;
use App\RocketCandy\Contracts\Tag;
use App\RocketCandy\Exceptions\FailedJobCreateException;
use App\RocketCandy\Exceptions\NaughtyBoyException;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Redirect;
use Laracasts\Flash\Flash;
```
However it doesn't look great. I like to order them based on the length of of the namespace:
```
use Laracasts\Flash\Flash;
use App\Http\Requests\JobRequest;
use App\RocketCandy\Contracts\Bid;
use App\RocketCandy\Contracts\Job;
use App\RocketCandy\Contracts\Tag;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Redirect;
use App\RocketCandy\Exceptions\NaughtyBoyException;
use App\RocketCandy\Exceptions\FailedJobCreateException;
```

Any chance this feature could be built in? A lot of us in the Laravel community quite like ordering on this basis.

**Comment by ccirello** [comment]
The laravel mode is deprecated in php.tools. Laravel practices are usually brain dead, but even an arrogant b*stard like me acknowledge their popularity. 

Consider enabling `SortUseNameSpace` in users configuration file for this package.

**Comment by ccirello** [comment]
In configuration file:

```
...
"passes":["SortUseNameSpace"],
...
```

**Comment by olimorris** [comment]
Works great!

Well the framework is at least now PSR-2 but it took a while in getting there. The rest of it rocks though :)

**Comment by kokokurak** [comment]
I didn't quite understand the conclusion on this one. Is sorting by length available or not? I prefer to have my imports sorted this way as well.

**Comment by ccirello** [comment]
Have you tried SortUseNameSpace?

**Comment by kokokurak** [comment]
Yes I did. Here's my settings file:
```
{
	"autocomplete": true,
	"enable_auto_align": true,
	"format_on_save": true,
	"passes":
	[
		"SortUseNameSpace"
	],
	"php_bin": "/usr/local/bin/php",
	"psr1": true,
	"psr2": true,
	"version": 4
}
```
When I save the file, my imports are sorted alphabetically, but not respecting the length. It happens whether I put `SortUseNameSpace` to `passes` or not.

**Comment by ccirello** [comment]
Open a new issue with this potential bug. Ensure you provide a snippet of source code that fails, and the console output with the option `"debug":true` in the configuration file.
