### ISSUE TITLE
Problem with PSR-2

### ISSUE THREAD

**Issue by nntoan** [phpfmt/sublime-phpfmt#187]
Hello there,

I got some troubles with PSR-2 coding style.

These code below formatted with phpfmt:

```php
try {
    switch ($subCommand) {
    case 'environments':
        $exitCode = $this->listEnvironments();
        break;

    default:
        throw new Exception('The Type of Elements to List is needed.');
        break;
    }
} catch (Exception $e) {
    Console::output('<red>' . $e->getMessage() . '</red>', 1, 2);
}
```

As you see, there is a little issue with indetation from `switch ... case`

How could I resolve this?

**Comment by ccirello** [comment]
Consider activating the additional transformation "ReindentSwitchBlocks" in command palette.

**Comment by nntoan** [comment]
@ccirello : Thank for your response, but I can't found "phpfmt: reindent switch block..." in command palette. How to add it manually in user settings file.

**Comment by ccirello** [comment]
@nntoan use the palette option `phpfmt: toggle additional transformations`-inside of it will be the option to activate the reindent
