### ISSUE TITLE
Laravel Comments in Arrays

### ISSUE THREAD

**Issue by sonuku** [phpfmt/sublime-phpfmt#188]
Hi there.

In Laravel there is a coding style that puts comments inbetween large config arrays.
This can get a bit ugly if everything is aligning or not aligning.

Is it possible to suggest AlignDoubleArrow stops matching parent vertical alignment at a /** block or \n ? Like how AlignEquals stops at new lines.

[example](http://i.imgur.com/JdoKWFE.png)

Alternatively, i'd like to stop all alignment transformation to arrays. Disabling AlignDoubleArrow just reverses the behaviour rather than skips it.

**Comment by ccirello** [comment]
Laravel and its practices are deprecated in php.tools. If you come up with a PR, I will gladly merge it. This might be relevant for you: https://github.com/phpfmt/php.tools/blob/master/src/Additionals/AlignDoubleSlashComments.php
