### ISSUE TITLE
DocBlock for first method

### ISSUE THREAD

**Issue by abhimanyusharma003** [phpfmt/sublime-phpfmt#189]
For some reasons it is not generating DocBlock for first method in the class.

```php
class BlogController
{

    public function reports($request)
    {
        return $request;
    }
}
```

PS: Nice extension.

**Comment by ccirello** [comment]
@abhimanyusharma003 I could not reproduce this bug. I need more context. Please, paste here the output of `phpfmt: troubleshoot information` and the configuration file.

**Comment by abhimanyusharma003** [comment]
Here are all the info

* phpfmt: troubleshoot information http://i.imgur.com/wMcRGnH.png
* Settings https://gist.github.com/anonymous/4c9c86713c1b413dc952
* Test file https://gist.github.com/anonymous/8f6b5b067367ec62067d

Yes right now i'm using Windows 10

**Comment by ccirello** [comment]
Any returns in the console? Seems good for me.

**Comment by abhimanyusharma003** [comment]
No nothing. Is there any thing I need to take care in php settings ?

**Comment by ccirello** [comment]
In plugin configuration file, please add `"debug":true` and paste here the output of console.

**Comment by abhimanyusharma003** [comment]
This might help you, look like there is some error at https://gist.github.com/anonymous/8b8136f17379c7a62d83#file-gistfile1-txt-L94 please let me know further.

**Comment by ccirello** [comment]
What happens when you try to format the file using the incantation out putted in the console straight on the command line?

**Comment by abhimanyusharma003** [comment]
I think I got the error and sorry for not providing this at the first time. My actual file look like this

```php
<?php

/**
 * @author Abhimanyu Sharma <abhimanyusharma003@gmail.com>
 */

class BlogController
{

    public function reports($request)
    {
        return $request;
    }
}
```

as soon as remove

```
/**
 * @author Abhimanyu Sharma <abhimanyusharma003@gmail.com>
 */
```

it generates the docblock for function, otherwise it fails to do that.

**Comment by ccirello** [comment]
@abhimanyusharma003 upgrade to https://github.com/phpfmt/sublime-phpfmt/releases/tag/7.12.0

**Comment by abhimanyusharma003** [comment]
Many thanks :)
