### ISSUE TITLE
php short tag not work

### ISSUE THREAD

**Issue by scsidisk** [phpfmt/sublime-phpfmt#190]
In Yii2 use php short tag like `<?=` ,fortmart it not work.

**Comment by scsidisk** [comment]
I saw in `.py` set `"psr1"=true` will add `-dshort_open_tag="on"` ,i add it, sublime text3 is still not work.

**Comment by ccirello** [comment]
Can you provide a piece of code so I try to reproduce this bug?

**Comment by scsidisk** [comment]
```php
<?php
use yii\widgets\DetailView;
?>
                        <div class="body">

<?=DetailView::widget([
'model'      => $model,
'attributes' => [
'id',
[
'label' => 'name',
'value' => $model->name,
],
],
]);?>
</div>
```

**Comment by ccirello** [comment]
@scsidisk please, upgrade to https://github.com/phpfmt/sublime-phpfmt/releases/tag/7.13.0

**Comment by scsidisk** [comment]
thanks.
