### ISSUE TITLE
Spaces after (int) and (string) in PHP

### ISSUE THREAD

**Issue by arnisjuraga** [phpfmt/sublime-phpfmt#191]
Hi!

When using conversion to (string) or (int), formatter adds extra space after:

~~~php
(int)$variable;
~~~

becomes:

~~~php
(int) $variable;
~~~

From http://php.net/manual/en/language.types.type-juggling.php it seems to be the "right" format?
Mostly, I have seen _everyone_ is using casting without extra space.

Can it be changed or configured to "not add extra space" after type casting?

**Comment by ccirello** [comment]
There's not such toggle, and I will not dare saying which is the right way. I know I followed the manuals and official styles everywhere. 

You can however create an Additional pass in php.tools that make this transformation. I will merge a PR gladly.
