### ISSUE TITLE
The OrderUseClauses need to be fixed

### ISSUE THREAD

**Issue by SelimSalihovic** [phpfmt/sublime-phpfmt#192]
I think the OrderUseClauses needs to be fixed. It should just order them according to their length from shortest to longest but not delete some of them. Currently I just have 
```
"excludes":
	[
		"OrderUseClauses"
	]
```

like you advised another guy to do in another issue.

 For example:

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class PagesController extends Controller
{

    public function index()
    {
        return view('index');
    }

}

```

Here I lose use Illuminate\Http\Request; completely. What I would like is to just either leave it that way and order them. Maybe you could introduce some kind of ordering by group too.

For example:

```
use App\AnotherPost;
use App\Post;

use App\AnotherBook;
use App\Book;
```

Would transform to:

```
use App\Post;
use App\AnotherPost;

use App\Book;
use App\AnotherBook;
```

Let me know what you think.

**Comment by ccirello** [comment]
Why do you want to keep an unused imported class?

**Comment by ccirello** [comment]
> Maybe you could introduce some kind of ordering by group too.

If you manage to produce a PR adding this feature, I will merge it gladly.

**Comment by SelimSalihovic** [comment]
I will try to finish the ordering by group in the following days and submit a PR once I test it out. As for the problem up top, you were absolutely right - I did not read the description of OrderUseClauses and expected it to just be used for the ordering and not for deleting unused ones too. My bad.
