### ISSUE TITLE
formatter not working with psr1/2 enabled

### ISSUE THREAD

**Issue by LanceKroepke** [phpfmt/sublime-phpfmt#196]
hi there!

i'm getting this strange "ERROR: manifest length read was "367385" should be "1130320972"" on phpfmt via pressing the F11 to reformat.

my config looks like this:

    {
	"format_on_save": false,
	"passes":
	[
		"ReindentSwitchBlocks"
	],
	"psr1": true,
	"psr1_naming": true,
	"psr2": true,
        "version": 4
    }

my code to reformat is.

    <?php

    class stack {
                public $fields;
        public $limit;

                public function __construct()		 {
                $this->fields = array();
    }

        public function push($item)  {
            array_unshift($this->fields, $item);
        }

        public function pop()  {
            if ($this->isempty()) {			throw new RunTimeException('Stack is empty!');
            } else {
                return array_shift($this->stack);
            }
        }

        public function top() {
                return current($this->fields);
        }

        protected function isempty() {
                return empty($this->fields);
        }
        }

since this is the first time i'm really using phpfmt i can't determine whether it was working at all.

**Comment by LanceKroepke** [comment]
oh yeah

in the console i can sea this:

    phpfmt (php_ver) err:

**Comment by ccirello** [comment]
Reinstall the plugin and test again please. It seems a bad install

**Comment by LanceKroepke** [comment]
ok, so i've reinstalled it
still getting this message: ERROR: manifest length read was "367385" should be "1130320972"

I am running:
lance@lancemashine ~ $ php -v
PHP 5.6.13 (cli) (built: Sep  3 2015 18:51:25) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

and I am able to run php from command line. (does this already implicates that php is configured in the PATH variable?)

**Comment by ccirello** [comment]
refer to https://github.com/phpfmt/sublime-phpfmt/issues/68

Is phar extension enabled correctly?

**Comment by LanceKroepke** [comment]
well since I've already ran into issues with phar due to using composer/laravel and in the end it all worked as intented i thought it would be setup right.

enabling the debug option however gives me:

    cmd_fmt:  ['php', '-dshort_open_tag=On', '/home/lance/.config/sublime-text-3/Packages/phpfmt/fmt.phar', '--config=/home/lance/.config/sublime-text-3/Packages/phpfmt/php.tools.ini', '--psr1', '--psr1-naming', '--psr2', '--visibility_order', '--smart_linebreak_after_curly', '--passes=ReindentSwitchBlocks', '-v', '-o=-', '-']
    p:
     0
    err:

**Comment by ccirello** [comment]
you are running PHP from path. Try running this call manually on your terminal. You might get an insight of what's happening.

**Comment by LanceKroepke** [comment]
sure, unfortunately this does not change anything at all, still getting the same error

    lance@lancemashine ~ :( $ php -dshort_open_tag=On /home/lance/.config/sublime-text-3/Packages/phpfmt/fmt.phar --config=/home/lance/.config/sublime-text-3/Packages/phpfmt/php.tools.ini --psr1 --psr1-naming --psr2 --visibility_order --smart_linebreak_after_curly --passes=ReindentSwitchBlocks -v -o=- -
ERROR: manifest length read was "367385" should be "1130320972


    lance@lancemashine ~ :( $ php -dshort_open_tag=On /home/lance/.config/sublime-text-3/Packages/phpfmt/fmt.phar
ERROR: manifest length read was "367385" should be "1130320972

**Comment by ccirello** [comment]
Ok. Using this php, please check both version and if phar extension is enabled.

**Comment by LanceKroepke** [comment]
i will try reinstalling php and enabling phar from start

**Comment by LanceKroepke** [comment]
that fixed it!!

formatting now works smooth. thanks for your help!!
one last question: 
i've set the phpfmt

    "indent_with_space": false,

and in the sublime config i have:

        "translate_tabs_to_spaces": false,

to indent with tabs.

but it keeps indenting with 4 spaces. am I missing something?

**Comment by ccirello** [comment]
yes. PSR2 demands indentation with spaces instead of tabs.
