### ISSUE TITLE
How to use a 'Transformations' in settings? What to include in `phpfmt.sublime-settings`?

### ISSUE THREAD

**Issue by Commenter123** [phpfmt/sublime-phpfmt#198]
So there are all these awesome 'Transformations' [available](https://github.com/phpfmt/sublime-phpfmt/blob/6113328fe546f24cf3248243643869ad8da7983a/README.md#currently-supported-transformations), but how to actually apply one?
I guess they have to be added to the `passes` array in user settings, correct?
E.g.:
```
"passes":
	[
		"RemoveUseLeadingSlash",
		"SpaceBetweenMethods",
		"RestoreComments",
		"MergeElseIf",
		"ReindentSwitchBlocks"
	],
```

Also it would be awesome to get detailed docs on how to use the `phpfmt.sublime-settings` file:
  - Add an example for every 'Transformation'
  - List all available commands with their purpose (`php_bin`, `passes`, `version`, ..)

My settings file currently includes (old?) stuff like `"psr1": false`. Should this be removed?

Thanks for this awesome plugin! :heart:

**Comment by ccirello** [comment]
Consider using `phpfmt: toggle additional transformations`

Configuration should be handled through command palette. 

Examples of transformations can be found at phpfmt/php.tools

**Comment by Commenter123** [comment]
OK, awesome! :)

One quick question regarding `StrictBehavior` transformation: Docs say `Danger! This pass leads to behavior change.` What exactly does that mean and how could it impact the code?

**Comment by ccirello** [comment]
Exactly what's said. If you activate it, your code might get changed in a way it changes its behavior. In case of strict comparisons, stricter comparisons may lead to more false evaluations.
