### ISSUE TITLE
'RestoreComments' not mentioned in README

### ISSUE THREAD

**Issue by Commenter123** [phpfmt/sublime-phpfmt#199]
Transformation `RestoreComments` is not mentioned in README

**Comment by ccirello** [comment]
And it is not meant to be. It is a specific use case, and likely will be deprecated in future.

**Comment by Commenter123** [comment]
Why deprecated? `RestoreComments` should be enabled by default in my opinion.

**Comment by ccirello** [comment]
Because RestoreComments undo the indentation of the content of comments, it essentially defeats the purpose of a pretty printer.

**Comment by Commenter123** [comment]
`RestoreComments` doesn't undo anything. It completely ignores the indentation of comments.
If `RestoreComments` is removed, all comments will completely lose their indentation.

**Comment by Commenter123** [comment]
See !87

**Comment by ccirello** [comment]
RestoreComments undo the automatic reindentation of comments. That's why it defeats the purpose of a pretty printer. The correct behavior is the same of gofmt, in which comments blocks have their contents indented once, and kept untouched after that. Not yet implemented in fmt.phar

**Comment by Commenter123** [comment]
So you say
```
/*if (true) {
echo 'Hi' . PHP_EOL;
if (false) {
echo 'Oh noes!' . PHP_EOL;
}
}*/
```
is the way a comment should look like?

**Comment by ccirello** [comment]
You need to lay down some context.

For raw code as:
```
$a = 0;
if (true) {
echo 'Hi' . PHP_EOL;
if (false) {
echo 'Oh noes!' . PHP_EOL;
}
$b = 0;
```

That has been commented as:
```
$a = 0;
/*
if (true) {
echo 'Hi' . PHP_EOL;
if (false) {
echo 'Oh noes!' . PHP_EOL;
}
*/
$b = 0;
```

It should be formatted as:
```
$a = 0;
/*
if (true) {
echo 'Hi' . PHP_EOL;
if (false) {
echo 'Oh noes!' . PHP_EOL;
}
*/
$b = 0;
```

For raw code:
```
$a = 0;
if (true) {
        echo 'Hi' . PHP_EOL;
        if (false) {
        echo 'Oh noes!' . PHP_EOL;
}
$b = 0;
```

That has been commented as:
```
$a = 0;
/*
if (true) {
        echo 'Hi' . PHP_EOL;
        if (false) {
        echo 'Oh noes!' . PHP_EOL;
}
*/
$b = 0;
```

Then, it should be reindented as:
```
$a = 0;
/*
        if (true) {
                echo 'Hi' . PHP_EOL;
                if (false) {
                echo 'Oh noes!' . PHP_EOL;
        }
*/
$b = 0;
```
and left alone after that.

**Comment by Commenter123** [comment]
Ahh, I see. Yes, that's what we need! :)
