### ISSUE TITLE
'AutoSemicolon' incorrectly inserts semicolon

### ISSUE THREAD

**Issue by Commenter123** [phpfmt/sublime-phpfmt#200]
`AutoSemicolon` incorrectly inserts a semicolon.

From:
```
$url = (
	isset($array['url'])
	? $array['url']
	: 'myurl123'
);
```

To:
```
$url = (
	isset($array['url']);
	? $array['url']
	: 'myurl123'
);
```

Notice the `;` right after `isset()`

**Comment by ccirello** [comment]
Please, upgrade to latest

**Comment by Commenter123** [comment]
You know what? You're awesome!! :heart: 
Thank you so much for this awesome project(s) :whale:

**Comment by ccirello** [comment]
@Commenter123 Thanks for using this plugin
