### ISSUE TITLE
Add `StripNewlineBeforeClassClose` and `StripNewlineBeforeCurlyClose`

### ISSUE THREAD

**Issue by Commenter123** [phpfmt/sublime-phpfmt#202]
Currently there are these two transformations available:
  - StripNewlineAfterClassOpen
  - StripNewlineAfterCurlyOpen

If both these transformations are enabled, this code only loses the linebreak right after `class Test {`, but not the linebreak before the closing `}` to `class`
```
class Test {

	private function test1() {
	}

	public function test2() {
	}

	private function test3() {
		echo 1;

	}

}
```

Expected result:
```
class Test {
	private function test1() {
	}

	public function test2() {
	}

	private function test3() {
		echo 1;
	}
}
```

**Comment by ccirello** [comment]
Patches are welcome. Please, feel free to produce such Pass.
