### ISSUE TITLE
I want to use tabs, not spaces, how to set?

### ISSUE THREAD

**Issue by unkang** [phpfmt/sublime-phpfmt#205]
I want to use tabs, not spaces, how to set?

**Comment by Shaked** [comment]
Hey, 

You can use `cmd + p` on a mac or `ctrl + p` on other platforms and search for `phpfmt: indentation with spaces`: 

![monosnap 2015-10-26 04-29-26](https://cloud.githubusercontent.com/assets/960015/10719940/55bb423c-7b9a-11e5-98dd-a7304f5b6e17.jpg)

This will prompt a input that will allow you to choose the number of spaces, leaving the box empty will default back to tabs: 

![phpfmt sublime-settings php tools 2015-10-26 04-32-22](https://cloud.githubusercontent.com/assets/960015/10719980/9e0ae434-7b9a-11e5-936c-cd565f69000c.jpg)

Which will change your user configuration to use: ```"indent_with_space": false```

Enjoy!
