### ISSUE TITLE
Infinite loop with namespaces

### ISSUE THREAD

**Issue by Lykegenes** [phpfmt/sublime-phpfmt#208]
Hi!

I'm using Laravel and I noticed that whenever I use namespace in this format `MyApp\Models\User::class` (instead of a string), there seems to be an infinite loop when processing the file. I then have to manually kill the `php` process.

Is there any setting i'm missing, or is this a bug?

Thanks!

**Comment by ccirello** [comment]
I need the configuration file, the snippet of code that fails and which call you are making.

**Comment by Lykegenes** [comment]
Here is my configuration file : 
```json
{
	"autocomplete": false,
	"autoimport": false,
	"format_on_save": true,
	"indent_with_space": 4,
	"laravel_deprecated_warning": true,
	"linebreak_after_namespace": true,
	"linebreak_between_methods": true,
	"passes":
	[
		"AutoSemicolon",
		"ClassToStatic",
		"IndentTernaryConditions",
		"MergeElseIf",
		"MergeNamespaceWithOpenTag",
		"RemoveUseLeadingSlash",
		"SpaceBetweenMethods",
		"ReindentSwitchBlocks"
	],
	"php_bin": "/usr/local/php5/bin/php",
	"psr2": true,
	"space_around_exclamation_mark": true,
	"version": 4
}
```

The file that fails can be found here : [Link](https://github.com/laravel/laravel/blob/master/config/app.php). Notice the `providers` and `aliases` arrays; they're the ones that cause the issue.

If there is anything else I can do to help...

**Comment by ccirello** [comment]
Please, upgrade to https://github.com/phpfmt/sublime-phpfmt/releases/tag/9.10.0

**Comment by Lykegenes** [comment]
It works! Thank you so much! :+1:
