### ISSUE TITLE
Add example .php.tools.ini

### ISSUE THREAD

**Issue by amenadiel** [phpfmt/sublime-phpfmt#209]
Hi. I struggled for a bit to replicate the plugin configuration with the per-project-settings format. I wish there was an example ini file to look at. 

Here's mine, btw

```sh
psr2=1
indent_with_space=4
smart_linebreak_after_curly=1
enable_auto_align=1
lint-before=1

passes = SpaceBetweenMethods, ReindentSwitchBlocks, PSR2EmptyFunction,  ReindentAndAlignObjOps, ReindentSwitchBlocks, ShortArray, AutoSemicolon, AddMissingParentheses
```

**Comment by ccirello** [comment]
Please, open a PR with this change.

**Comment by amenadiel** [comment]
I would if I knew what's supposed to go inside said file. I just went trial and error to get a working sample, but it's far from complete.

**Comment by ccirello** [comment]
The .php.tools.ini reads exactly the same parameters of cli call. So, for instance, if you have "--psr2" parameter, in ini file it will be "psr2=1"

You can take a look at the ini file from phpfmt/php.tools in src/  folder there you have a working example.
