### ISSUE TITLE
Space around exclamation mark not working

### ISSUE THREAD

**Issue by Lykegenes** [phpfmt/sublime-phpfmt#210]
Hello again!

I searched in the previously closed issues, and found two different (and not documented) settings for this : 
`"space_around_exclamation_mark": true,` and `"passes: [ "SpaceAroundExclamationMark" ],`

The first one doesn't seem to do anything (it removes the spaces). The second one doesn't remove the spaces around the exclamation mark anymore (when I add them manually), but doesn't add them either if they're missing. Also, if I add more than one space (like this : `if(_!____$var)` ), it doesn't remove the extra spaces so that there is only one left on each side.

Here's my full config : 
```json
{
	"autocomplete": false,
	"autoimport": false,
	"format_on_save": true,
	"indent_with_space": 4,
	"laravel_deprecated_warning": true,
	"linebreak_after_namespace": true,
	"linebreak_between_methods": true,
	"passes":
	[
		"AddMissingParentheses",
		"AutoSemicolon",
		"ClassToStatic",
		"IndentTernaryConditions",
		"MergeElseIf",
		"MergeNamespaceWithOpenTag",
		"RemoveUseLeadingSlash",
		"ReturnNull",
		"SpaceAroundExclamationMark",
		"SpaceBetweenMethods",
		"StripNewlineAfterClassOpen",
		"StripNewlineAfterCurlyOpen",
		"ReindentSwitchBlocks"
	],
	"php_bin": "/usr/local/php5/bin/php",
	"psr2": true,
	"space_around_exclamation_mark": true,
	"version": 4
}
```

**Comment by ccirello** [comment]
It seems a bug. We are going to fix it ASAP.

**Comment by ccirello** [comment]
Please, upgrade to https://github.com/phpfmt/sublime-phpfmt/releases/tag/9.12.0
