### ISSUE TITLE
I wanna keep the unused use statement

### ISSUE THREAD

**Issue by gfd6th** [phpfmt/sublime-phpfmt#214]
Hi, I have fixed this issue before with the following configures

{
...
    "excludes": ["OrderUseClauses", "SortUseNameSpace"],
...
},

But it doesn't work on new version 9.18.0.

**Comment by ccirello** [comment]
I cannot reproduce this bug. Please provide me with failing source code and complete configuration.

**Comment by ccirello** [comment]
@gfd6th Add to your configuration file:
```
...
"excludes": ["OrderAndRemoveUseClauses"],
...
```
