### ISSUE TITLE
Null inputs error

### ISSUE THREAD

**Issue by QiiSyhx** [phpfmt/sublime-phpfmt#215]
error information:
phpfmt (php_ver) cmd:
 ['D:/phpStudy/php56n/php.exe', '-v']
phpfmt (php_ver) out:
 PHP 5.6.1 (cli) (built: Sep 24 2014 18:58:19) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies

phpfmt (php_ver) err:
 
error: Null inputs. (diff_main)

configs:
{
	"autocomplete": true,
	"format_on_save": true,
	"php_bin": "D:/phpStudy/php56n/php.exe",
	"psr1": true,
	"version": 4
}

or
{
	"enable_auto_align": true,
	"passes":
	[
		"ReindentSwitchBlocks"
	],
	"version": 4,
	"php_bin": "D:/phpStudy/php56n/php.exe",
}
I try to change the configs,but it dosen't work.

**Comment by ccirello** [comment]
Provide me with the failing source code. It is a bug in the buffer updater.

**Comment by QiiSyhx** [comment]
sorry, I had a bug in the source code,so phpfmt did not work.
