### ISSUE TITLE
remove extra semicolon & any other on format

### ISSUE THREAD

**Issue by ctf0** [phpfmt/sublime-phpfmt#217]
is there away for the plugin to check if there something like an extra semicolon and delete it accordingly instead of just giving an `err` , we can use sublimelinter-php for something like that instead of the plugin trying to figure it out.

i mean something like
```php
public function xxx() {
    // code
};
```
will result into
```php
public function xxx() {
    // code
}
; // < this should be removed
```

**Comment by ccirello** [comment]
Can you elaborate further on the utility of such feature? I am seeing this as a tool to handle few exceptional cases which the cost of developing it does not outweigh the cost of addressing them manually.

**Comment by ctf0** [comment]
i understand that and thats why i suggested using something like the linter as a hook to figure out the error and fix it, but again if its too big of a feature then its okay you can ignore it.

**Comment by ccirello** [comment]
Do you think you can provide a patch using phpcbf?

**Comment by ctf0** [comment]
unfortunately if i knew how i would have made it and send you the PR already :(.

**Comment by ccirello** [comment]
oh I see. Maybe @Shaked would like to take a look at it?

**Comment by ctf0** [comment]
btw here is what i had in mind about the linter
https://packagecontrol.io/packages/Semicolon

**Comment by Shaked** [comment]
Maybe we should explicitly state when the semi colon should be removed ?

**Comment by ccirello** [comment]
Makes sense to me. @Shaked could you please address this with @ctf0 ?

**Comment by Shaked** [comment]
So first I would like to make sure that we don't redo the Semicolon plugin. This will only remove existing and irrelevant semi colons. 

As well, it is important to understand when a semi colon has to be removed. If we use a hook then we decide not to be responsible on that and let the sublime-linter do that. Otherwise, we have to make sure what are the possible scenarios for that to happen. I would definitely vote for the sublime listener as it is already implemented and should be easier to address, does it make sense for you @ccirello @ctf0 ?

**Comment by ccirello** [comment]
I don't know whether it is possible, but I would try to do it internally to fmt.phar.

**Comment by ctf0** [comment]
@Shaked if we gonna use the linter yes ofcourse `fmt` wont be responsible for any misbehave from the linter side, but for the other option i have no idea what exactly will it behave.

**Comment by Shaked** [comment]
Ok so maybe it would be smart to just follow the linter in that case when there is an extra semi colon.

**Comment by ccirello** [comment]
@Shaked maybe the fmt.phar could do the trick through memo variables:
https://github.com/phpfmt/fmt/blob/master/src/Core/TwoCommandsInSameLine.php#L30-L38

**Comment by ccirello** [comment]
I guess it needs only to have the previous closing curly brace checked for closures. If semicolon, and before it was a closing curly brace of a closure, drop the semicolon. 

This transformation, though I would add as an Additional, extending TwoCommandsInSameLine, but short-circuit it.

**Comment by ccirello** [comment]
Upgrade to: https://github.com/phpfmt/sublime-phpfmt/releases/tag/9.21.0
And activate the additional pass: RemoveSemicolonAfterCurly
