### ISSUE TITLE
use clauses annotations Doctrine

### ISSUE THREAD

**Issue by spohess** [phpfmt/sublime-phpfmt#218]
Hi,

The phpfmt do not recognize the annotattions of Docretine and remove the use clauses.

```
use Gedmo\Mapping\Annotation AS Gedmo;
use Doctrine\ORM\Mapping AS ORM;

/**
 * @ORM\Entity
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 * @ORM\Table(name="entity")
 */
Class Entity {
}
```

**Comment by ccirello** [comment]
I am sorry for this bug. It is going to be fixed as soon as possible.

**Comment by spohess** [comment]
Thanks a lot, the plugin is amazing. If need help let me know.
