### ISSUE TITLE
AlignPHPCode can not use indent_with_space: 4 setting

### ISSUE THREAD

**Issue by coolbf** [phpfmt/sublime-phpfmt#223]
![before_save](https://cloud.githubusercontent.com/assets/1628336/12005506/51907f14-abe3-11e5-822b-18f8a390d5f3.jpg)
![end_save](https://cloud.githubusercontent.com/assets/1628336/12005507/5423f8be-abe3-11e5-9ee5-5494c9c5d8be.png)

my config
{
    "autocomplete": true,
    "enable_auto_align": true,
    "format_on_save": true,
    "indent_with_space": 4,
    "passes":
    [
        "AlignDoubleSlashComments",
        "AlignGroupDoubleArrow",
        "GeneratePHPDoc",
        "IndentTernaryConditions",
        "AlignPHPCode",
        "PrettyPrintDocBlocks"
    ],
    "php_bin": "/usr/local/php5-5.6.11-20150710-223902/bin/php",
    "psr2": true,
    "readini": true,
    "version": 1
}

**Comment by coolbf** [comment]
I use the ignore_list setting, thanks

**Comment by ccirello** [comment]
Provide a piece/gist of code for bug reproduction.

**Comment by ccirello** [comment]
hi @coolbf I am closing this issue due to lack of response. If you still face this issue, please open it again.
