### ISSUE TITLE
remove duplicated cmnds

### ISSUE THREAD

**Issue by ctf0** [phpfmt/sublime-phpfmt#226]
hi again,
right now the plugin has so many duplicated cmnds like
`enable/disable additional trans.. & toggle additional trans..` which have the same settings

also some of the settings in the additional transformations are the same like
`aligndoubleslash & align typehint` which align the `//` comments
or
`AlignDoubleArrow & AlignGroupDoubleArrow' which align the `=>`

**Comment by ccirello** [comment]
I am keeping the old repeated commands so to avoid users used to one of them to miss them between upgrades. 

This might be addressed in the next major release.
