### ISSUE TITLE
Passes vs. settings

### ISSUE THREAD

**Issue by kokokurak** [phpfmt/sublime-phpfmt#227]
What is the difference between `passes` array and some of settings? It seems like there are settings for some passes, but not for all. What is the idea behind it and which one takes priority?

**Comment by ccirello** [comment]
Passes are given to `--passes` when relayed to fmt.phar. The other options are either converted into passes or additional parameters to the phar. 

The precedence between passes are describe here: https://github.com/phpfmt/fmt/blob/master/src/Core/BaseCodeFormatter.php
