### ISSUE TITLE
Unwanted passes are being fired

### ISSUE THREAD

**Issue by kokokurak** [phpfmt/sublime-phpfmt#230]
I'm using `.php.tools.ini` file to set formatting on my project. The content of this file is:
```
debug=1
passes=ShortArray,SortUseNameSpace,DoubleToSingleQuote,ReturnNull,SpaceBetweenMethods
no-backup=1
format_on_save=1
```
For some reason, the passes used by `phpfmt` are:
```
Used passes: EliminateDuplicatedEmptyLines, RTrim, ShortArray, LeftAlignComment, ReindentComments, ReindentEqual, Reindent, ReindentObjOps, ReindentColonBlocks, SplitCurlyCloseAndTokens, ResizeSpaces, StripExtraCommaInList, MergeDoubleArrowAndArray, MergeCurlyCloseAndDoWhile, MergeParenCloseWithCurlyOpen, NormalizeLnAndLtrimLines, ExtraCommaInArray, SmartLnAfterCurlyOpen, AddMissingCurlyBraces, OrderAndRemoveUseClauses, NormalizeIsNotEquals, RemoveIncludeParentheses, TwoCommandsInSameLine
```
Where do they come from? My user settings for `phpfmt` are just those:
```
{
	"php_bin": "/usr/local/bin/php",
	"debug": true,
	"readini": true,
	"version": 4
}
```

**Comment by ccirello** [comment]
They are the core passes. A baseline of transformations that guarantees certain code style before running the additional passes.

**Comment by kokokurak** [comment]
Is it documented?

**Comment by ccirello** [comment]
Core passes are not documented because they're baselines. The additional passes are.

**Comment by kokokurak** [comment]
I think it would be good idea to improve documentation. I don't know what are the baselines and I don't want my code to be formatted in some way I don't want it to. Following all transformations is not an option. It would be great to organize passes / options relations as well, in other words: which options enable which passes.

**Comment by ccirello** [comment]
I see. I guess it is not obvious in the README.md that it works only for K&R and PSR2. Anything else is not officially supported. The transformations are not idempotent, meaning you cannot apply just one of them and expect the same result. If you call fmt.phar help screen, you can have what you just asked: for each additional pass it will provide an explanation and an example. 

`php fmt.phar --list` and `php fmt.phar --help-pass`.
