### ISSUE TITLE
Spaces inside control structures

### ISSUE THREAD

**Issue by kokokurak** [phpfmt/sublime-phpfmt#232]
Is there any pass to automatically put spaces inside control structures, like below?
```php
if ( $condition ) {
```

**Comment by ccirello** [comment]
Not yet. Do you want to write it? I will merge into phpfmt/fmt gladly.

**Comment by ccirello** [comment]
I leave this open for few more days to see if anyone volunteers doing it.

**Comment by kokokurak** [comment]
I'm too short on time to learn this project.

**Comment by ccirello** [comment]
Me too.  :)

**Comment by ccirello** [comment]
If someone wants to pick it to do, just open a PR. Closing the issue.
