### ISSUE TITLE
commit 42d61593 broke the package

### ISSUE THREAD

**Issue by windevalley** [phpfmt/sublime-phpfmt#233]
The commit change `print("phpfmt (php_ver) cmd:\n", cmd_ver)` to `print_debug("phpfmt (php_ver) cmd:\n", cmd_ver)` cause error like:

File ".../sublime-text-3/Packages/phpfmt/phpfmt.py", line 134, in dofmt
    print_debug("phpfmt (php_ver) cmd:\n", cmd_ver)
TypeError: print_debug() takes 1 positional argument but 2 were given

**Comment by ctf0** [comment]
same here :(

**Comment by sonus** [comment]
It happened to me too

**Comment by ccirello** [comment]
Please, upgrade to https://github.com/phpfmt/sublime-phpfmt/releases/tag/10.0.1
