### ISSUE TITLE
Rebuild autocomplete database

### ISSUE THREAD

**Issue by RushabhJoshi** [phpfmt/sublime-phpfmt#240]
Hello,

I accidentally build database in my projects root.
because of this my sublime is getting slow.

should I store database per project?
how do I remove this?
what is the best practice?

**Comment by ccirello** [comment]
Have you considered disabling `phpfmt: toggle autocomplete`? 

The file you must look for to delete is "oracle.sqlite"

The best practice is having one per project. When creating the Oracle file, make sure you specify the correct directory.
