### ISSUE TITLE
How to turn off transformations?

### ISSUE THREAD

**Issue by lukeed** [phpfmt/sublime-phpfmt#241]
Specifically, I want to remove the Alphabetical transformation because it's a pain in the ass. =)

Looked through the previous issues. Adding an `excludes` key to my config doesn't do anything. Additionally, the "toggle excluded transformations" command doesn't work either.

Thanks!

(PS, would be great to separate the alphabetical sort from the length sort)

**Comment by ccirello** [comment]
There is not such transformation named `Alphabetical`. What are you referring yourself to?

**Comment by lukeed** [comment]
Oh, worth nothing I am intentionally targeting PSR2 (Laravel standard), but would like to disable this specific transformation.

**Comment by lukeed** [comment]
Did not mean `Alphabetical` as the name of the transformation, sorry.

"OrderUseClauses" and "SortUseNameSpace".

**Comment by ccirello** [comment]
Why don't you simple enable `SortUseNameSpace`?

**Comment by lukeed** [comment]
How? And I actually want to *disable* it.

**Comment by ccirello** [comment]
You can disable both transformations by adding both to exclude.
```
	"excludes":
	[
		"SortUseNameSpace",
		"OrderAndRemoveUseClauses"
	],
```

**Comment by lukeed** [comment]
Ok, it was `OrderAndRemoveUseClauses` that I needed to included. 

`OrderUseClauses` and `SortUseNameSpace` weren't enough on their own.

Thanks!
