### ISSUE TITLE
format no work with &

### ISSUE THREAD

**Issue by spohess** [phpfmt/sublime-phpfmt#242]
#Hi,

In my code I have this line: `oci_bind_by_name($stmt, ":ID", &$id, 20);`
With this line the format do not work. I make a few tests and find that problem is the `&`

**Comment by ccirello** [comment]
Works fine here - could you please share more context? Surrounding code and configuration?

**Comment by spohess** [comment]
This is de method

`public function insert($array)
    {
        $campos = array_keys($array);
        $values = array_values($array);
        foreach ($values as $key => $value) {
            $values[$key] = "'" . addslashes(str_replace('\'', '\"', $value)) . "'";
        }
        $query = "
            INSERT INTO {$this->tabela} (
                {$this->cpId},
                " . implode(',', $campos) . ",
                {$this->created}
            ) VALUES (
                {$this->sequence}.NEXTVAL,
                " . implode(',', $values) . ",
                SYSDATE
            ) RETURNING {$this->cpId} INTO :ID
        ";
        $stmt = oci_parse($this->db->conn_id, $query);
        oci_bind_by_name($stmt, ":ID", &$id, 20);
        oci_execute($stmt);
        oci_free_statement($stmt);
        return $id;
    }`

Works only I remove the `&`.

Thanks for help!

**Comment by ccirello** [comment]
OK. You are trying to format a code with a syntax error. It's the invalid `&`. Not a phpfmt bug.

**Comment by spohess** [comment]
It's not invalid

$a = new Foo; // $a is a pointer pointing to Foo object 0
$b = $a; // $b is a pointer pointing to Foo object 0, however, $b is a copy of $a
$c = &$a; // $c and $a are now references of a pointer pointing to Foo object 0

http://www.php.net/manual/en/language.oop5.references.php

**Comment by ccirello** [comment]
That's not what php linter says. Have you run the code, as is, in the php linter? I get a syntax error.

**Comment by spohess** [comment]
Hi man!

You alright. The real problem is in the version of php (5.2). This code is from a legacy sistem and in the php 5.2 the reference `&$id` still work.

Sorry about that.

**Comment by spohess** [comment]
Hi @ccirello!

Have any place that I can set for fmt ignore the `&$` and format the file?

Thanks!

**Comment by ccirello** [comment]
Formatting a file with syntax mistakes can lead to badly formatted code at best, or loss of code at worst.

You can try adding `AutoSemicolon` pass - which will disable linting.

**Comment by spohess** [comment]
Thanks @ccirello 

I'll leave this way. The code is too much ugly. Is more safe don't change the fmt.
