### ISSUE TITLE
how to stop the plugins to remove namesace?

### ISSUE THREAD

**Issue by ioriandy4** [phpfmt/sublime-phpfmt#243]
how to stop the plugins to remove namesace?I want to keep it even it's not used.

**Comment by Shaked** [comment]
Hey, 

Basically you should add exclude `OrderAndRemoveUseClauses`. This can be done via the menu (cmd\ctrl + P) -> toggle excluded transformations -> `OrderAndRemoveUseClauses`.

Another option is to open the settings file and add: 
```
  "excludes": [
    "OrderAndRemoveUseClauses"
  ],
```
