### ISSUE TITLE
inline php format problem

### ISSUE THREAD

**Issue by Goback** [phpfmt/sublime-phpfmt#245]
Hi,
this is the nice plugin,thank you really.
there is a small problem that i explain it via example,say we have this formatted code by plugin:

http://oi64.tinypic.com/rtdb40.jpg

while the expected result was:

http://oi67.tinypic.com/357rt6e.jpg

**Comment by ccirello** [comment]
Consider using `AlignPHPCode`. It might do want you want. 

Phpfmt formats PHP code, not HTML, thus it does not keep track of code around PHP blocks (`<?php... php?>`).
