### ISSUE TITLE
syntax error when using class const(key word) in switch statement

### ISSUE THREAD

**Issue by up9cloud** [phpfmt/sublime-phpfmt#247]
```php
<?php

switch ($a) {
	case 'value':
$b = A::DEFAULT;
$b = A::BREAK;
$b = A::CASE;
		break;
}
```

php -v
```
PHP 7.0.2 (cli) (built: Jan  7 2016 10:40:21) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
```

btw is there any option to enable showing syntax error line?

**Comment by up9cloud** [comment]
i'm sorry, 

I rechecked my php path.

current phpfmt is using php55compat mode,

I change the path to v7.0.2, then work like charm.

**Comment by ccirello** [comment]
I am waiting PHP to become fully EOL to disable the php55compat mode.
