### ISSUE TITLE
More complete documentation

### ISSUE THREAD

**Issue by cheoAlejo** [phpfmt/sublime-phpfmt#248]
Please provide a more complete documentation on all commands. For example, i have no idea what **yoda mode** is, or **toggle visibility order**.

**Comment by Shaked** [comment]
Hello @cheoAlejo 

These are aliases for YodaComparisons (documented in README) and PSR2ModifierVisibilityStaticOrder (part of [PSR2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md)). 

Are there any other unclear commands? 

@ccirello - shall we add the old aliases a description that includes "alias of PassX"?  

Shaked

**Comment by ccirello** [comment]
I think old commands should he removed altogether from the interface. Internally we'd honor for old configuration files. This would help reducing confusion about them.

**Comment by cheoAlejo** [comment]
Thanks for the answer.

**Comment by ccirello** [comment]
@Shaked want give it try? and remove them?

**Comment by Shaked** [comment]
I am on it
