### ISSUE TITLE
Don't format comments

### ISSUE THREAD

**Issue by leonklingele** [phpfmt/sublime-phpfmt#87]
Often I want to temporarily disable a few lines of code.
Before reformatting using sublime-phpfmt:
```
/*if (true) {
	echo 'Hi' . PHP_EOL;
	if (false) {
		echo 'Oh noes!' . PHP_EOL;
	}
}*/
```
After reformatting:
```
/*if (true) {
echo 'Hi' . PHP_EOL;
if (false) {
echo 'Oh noes!' . PHP_EOL;
}
}*/
```
The latter is not only hard to read, but also screws up string indentation.
When removing the multiline comment, one has to manually re-indent the strings (e.g. SQL).
Setting `"comment_auto_align": true / false` did not help.

**Comment by dericofilho** [comment]
@leonklingele I am really sorry for the inconvenience. I don't have a prospect of time to solve this particular topic. Personally I do not feel it is as bug, but I understand many people think otherwise. I will try to work on a solution (likely a toggle) as soon as possible.

**Comment by leonklingele** [comment]
Ok, thank you.
What's the meaning of `comment_auto_align`?

**Comment by dericofilho** [comment]
It formats from this
```php
$line; // Comment 1
$longerline; // Comment 2
$evenlongerline; // Comment 3
```
to
```php
$line;                   // Comment 1
$longerline;         // Comment 2
$evenlongerline; // Comment 3
```

**Comment by dericofilho** [comment]
@leonklingele please, manually update to https://github.com/dericofilho/sublime-phpfmt/commit/a5b67f5eee99b4711f5118f2cfabcfecbbb1f8a5

Add manually the option `restore_comments` in your configuration file, and test. If this is what you want, I shall release a new version.

**Comment by leonklingele** [comment]
Hmm, does not work for me.
I set `"restore_comments": true`. Is this correct?

```
/*if (true) {
	echo 'Hi' . PHP_EOL;
	if (false) {
		echo 'Oh noes!' . PHP_EOL;
	}
}*/
```
still becomes
```
/*if (true) {
echo 'Hi' . PHP_EOL;
if (false) {
echo 'Oh noes!' . PHP_EOL;
}
}*/
```
Code in comments should't be formatted at all.

**Comment by dericofilho** [comment]
@leonklingele please, add the option `debug` to your configuration and paste here the output from console. The comment shouldn't have been touched with this `restore_comments` set to true.

**Comment by leonklingele** [comment]
```
Writing file [..]/Desktop/test.php with encoding UTF-8 (atomic)
ApplySyntax: Syntax already set to Packages/PHP/PHP.tmLanguage
phpfmt (oracle file): not found
phpfmt: [..]/Desktop/test.php
phpfmt (php version) out:
 PHP 5.5.14 (cli) (built: Sep  9 2014 19:09:25) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies

phpfmt (php version) err:
 
cmd_fmt:  ['php', '[..]/Library/Application Support/Sublime Text 3/Packages/phpfmt/fmt.phar', '--config=[..]/Library/Application Support/Sublime Text 3/Packages/phpfmt/php.tools.ini', '--visibility_order', '--smart_linebreak_after_curly', '--passes=MergeElseIf,RemoveUseLeadingSlash,PSR2LnAfterNamespace,RestoreComments', '--prepasses=SpaceBetweenMethods', '[..]/Desktop/test.php']
err:
 Formatting ...
.
 1 files total
Took 0s

Reloading [..]/Desktop/test.php
```

**Comment by dericofilho** [comment]
@leonklingele Thanks for the content. I will work more on this. Please, be patient.

**Comment by leonklingele** [comment]
Sorry @dericofilho. Everything works fine now.
Just had to restart Sublime. I'm not used to restart apps :smile:

**Comment by dericofilho** [comment]
@leonklingele OK. Use it for few days, and tell me if it is behaving the way you expect to.

**Comment by leonklingele** [comment]
Works perfectly! Haven't noticed any side effects.
Thank you for your fast support

**Comment by leonklingele** [comment]
`RestoreComments` seems to be deprecated now..
Reopening this issue as
```
/*if (true) {
    echo 'Hi' . PHP_EOL;
    if (false) {
        echo 'Oh noes!' . PHP_EOL;
    }
}*/
```
again reformats to
```
/*if (true) {
echo 'Hi' . PHP_EOL;
if (false) {
echo 'Oh noes!' . PHP_EOL;
}
}*/
```

Comments shouldn't be touched at all..

**Comment by ccirello** [comment]
Comments content shouldn't be formatted at all.  But RestoreComments is not the solution for this bug. I am open to merge PRs and suggestions. 

I believe gofmt behavior is the right one. Keeping content intact it indents the comment one level further, if already indented, keep it intact.

**Comment by Shaked** [comment]
@ccirello I am gonna take a look at this issue as well

**Comment by ccirello** [comment]
@Shaked what do you think of this? https://github.com/phpfmt/php.tools/commit/4c7b4cd294e26176d2f3a58079a34613840fcc41

**Comment by Shaked** [comment]
@ccirello good start. I have added 2 more test cases: https://github.com/phpfmt/php.tools/commit/d2326caccf526fb36aeedccd119b7ffb15c5c9b2

**Comment by ccirello** [comment]
It's debatable whether T_DOC_COMMENT should be target of this behavior. In the end, docblocks are mixed structures of free text and meta-code that describe following piece of code. I would remove the `/** ... */` case.

**Comment by ccirello** [comment]
@Shaked https://github.com/phpfmt/php.tools/commit/301b37cecace4dac650e0a30094a0d59282fe90f

**Comment by Shaked** [comment]
@ccirello I see your point, it does make sense actually!

**Comment by leonklingele** [comment]
Latest release introduced a new bug:

This:
```
function hello() {
	/*if (true) {
	    echo 'Hi' . PHP_EOL;
	    if (false) {
	        echo 'Oh noes!' . PHP_EOL;
	    }
	}*/

	/* Singleline comment */

	/*
		Another multiline comment
	*/

	return 'Hello';
}

echo hello();
```
now formats to:
```
function hello() {
	/*if (true) {
		    echo 'Hi' . PHP_EOL;
		    if (false) {
		        echo 'Oh noes!' . PHP_EOL;
		    }
		}*/

	/* Singleline comment */

	/*
			Another multiline comment
		*/

	return 'Hello';
}

echo hello();
```
And when we format that code again:
```
function hello() {
	/*if (true) {
			    echo 'Hi' . PHP_EOL;
			    if (false) {
			        echo 'Oh noes!' . PHP_EOL;
			    }
			}*/

	/* Singleline comment */

	/*
				Another multiline comment
			*/

	return 'Hello';
}

echo hello();
```

Notice the indentation changes to the two multiline comments.

**Comment by ccirello** [comment]
Changes reverted. Add RestoreComments added back.

**Comment by leonklingele** [comment]
:heart_eyes_cat:

**Comment by ccirello** [comment]
@leonklingele I stand by the interpretation that RestoreComments is not the solution. But because there is not a good solution right now, I leave this workaround available.
